CREATE DATABASE HealthClinic
GO
USE HealthClinic
--INICIO DAS TABELAS DE PONTA
CREATE TABLE tb_Prontuario(
	IdProntuario INT PRIMARY KEY IDENTITY,
	Historico TEXT,
)

CREATE TABLE tb_Clinica(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(200) NOT NULL,
	CNPJ VARCHAR(14) UNIQUE NOT NULL,
	RazaoSocial VARCHAR(80) NOT NULL,
	HorarioAbertura TIME NOT NULL,
	HorarioEncerramento TIME NOT NULL,
)

CREATE TABLE tb_Perfil(
	IdPerfil INT PRIMARY KEY IDENTITY,
	TipoDePerfil VARCHAR(80) NOT NULL
)

CREATE TABLE tb_Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdPerfil INT FOREIGN KEY REFERENCES tb_Perfil(IdPerfil) NOT NULL,
	Nome VARCHAR(150) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	Senha VARCHAR(80) NOT NULL
)

CREATE TABLE tb_Especialidade(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Especialidade VARCHAR(50) NOT NULL
)

CREATE TABLE tb_PlanoDeSaude(
	IdPlanoDeSaude INT PRIMARY KEY IDENTITY,
	PlanoDeSaude VARCHAR(70) NOT NULL
)

--INICIO DAS TABELAS DAS PROFISSÕES

CREATE TABLE tb_Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES tb_Usuario(IdUsuario) UNIQUE NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES tb_Especialidade(IdEspecialidade) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES tb_Clinica(IdClinica) NOT NULL,
	Salario MONEY NOT NULL,
	CRM VARCHAR(8) UNIQUE NOT NULL,
	Idade TINYINT NOT NULL
)

CREATE TABLE tb_Paciente(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdPlanoDeSaude INT FOREIGN KEY REFERENCES tb_PlanoDeSaude(IdPlanoDeSaude) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES tb_Usuario(IdUsuario) UNIQUE NOT NULL,
	DataDeNascimento DATE NOT NULL,
	Sexo BIT NOT NULL
)

CREATE TABLE tb_administrador(
	IdAdmin INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES tb_Usuario(IdUsuario) UNIQUE NOT NULL,
)

--FIM DAS TABELAS DOS TIPOS DE USUARIOS


CREATE TABLE tb_Agendamento(
	IdAgendamento INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES tb_Clinica(IdClinica) NOT NULL,
	IdAdmin INT FOREIGN KEY REFERENCES tb_Administrador(IdAdmin) NOT NULL,
	HorarioDaConsulta DATETIME NOT NULL
)


CREATE TABLE tb_Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdProntuario INT FOREIGN KEY REFERENCES tb_Prontuario(IdProntuario) NOT NULL,
	IdAgendamento INT FOREIGN KEY REFERENCES tb_Agendamento(IdAgendamento) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES tb_Paciente(IdPaciente) NOT NULL,
	IdMedico INT FOREIGN KEY REFERENCES tb_Medico(IdMedico) NOT NULL,
	Descricao TEXT NOT NULL
)

CREATE TABLE tb_Feedback(
	IdFeedBack INT PRIMARY KEY IDENTITY,
	IdPaciente INT FOREIGN KEY REFERENCES tb_Paciente(IdPaciente) NOT NULL,
	IdConsulta INT FOREIGN KEY REFERENCES tb_Consulta(IdConsulta) UNIQUE NOT NULL,
	Comentario TEXT NOT NULL
)
